tap "candid82/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "ack"
brew "apr-util"
brew "asdf"
brew "awscli"
brew "bash"
brew "bat"
brew "boost"
brew "brew-cask-completion"
brew "bundler-completion"
brew "candid82/brew/joker"
brew "ccat"
brew "clojure"
brew "clojurescript"
brew "cmake"
brew "cocoapods"
brew "composer"
brew "curl-openssl"
brew "deno"
brew "diff-so-fancy"
brew "docker-completion"
brew "docker-compose-completion"
brew "dos2unix"
brew "elixir"
brew "elm-format"
brew "elm"
brew "fontconfig"
brew "fzf"
brew "gd"
brew "gem-completion"
brew "gettext"
brew "git-flow"
brew "git"
brew "gnupg"
brew "go"
brew "gradle"
brew "graphicsmagick"
brew "graphviz"
brew "highlight"
brew "htop"
brew "httpie"
brew "hugo"
brew "icu4c"
brew "imagemagick"
brew "jo"
brew "jq"
brew "jupyter"
brew "kotlin"
brew "launchctl-completion"
brew "leiningen"
brew "libtool"
brew "libxml2"
brew "mad"
brew "mas"
brew "maven"
brew "mono"
brew "mr"
brew "ngrep"
brew "node"
brew "noti"
brew "nvm"
brew "ocaml"
brew "oniguruma"
brew "opam"
brew "open-completion"
brew "php-code-sniffer"
brew "php"
brew "pip-completion"
brew "pkg-config"
brew "plantuml"
brew "proselint"
brew "pwgen"
brew "python"
brew "ripgrep"
brew "rsync"
brew "rustup-init"
brew "scala"
brew "screen"
brew "smartypants"
brew "sox"
brew "subversion", link: false
brew "swiftlint"
brew "tasksh"
brew "the_platinum_searcher"
brew "the_silver_searcher"
brew "thefuck"
brew "tldr"
brew "tmate"
brew "tmux"
brew "typescript"
brew "vcsh"
brew "vim"
brew "watchman"
brew "wget"
brew "xcproj"
brew "yarn"
brew "youtube-dl"
brew "zplug"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "zsh"
cask "1password"
cask "adoptopenjdk"
cask "aerial"
cask "alfred"
cask "android-sdk"
cask "battle-net"
cask "bricklink-studio"
cask "calibre"
cask "discord"
cask "docker"
cask "dropbox"
cask "firefox"
cask "font-alegreya-sans"
cask "font-alegreya"
cask "font-barlow"
cask "font-charter"
cask "font-eb-garamond"
cask "font-et-book"
cask "font-fira-code"
cask "font-fira-mono"
cask "font-fira-sans"
cask "font-hack"
cask "font-ia-writer-duo"
cask "font-ia-writer-duospace"
cask "font-ia-writer-mono"
cask "font-ia-writer-quattro"
cask "font-ibm-plex"
cask "font-iosevka"
cask "font-jetbrains-mono"
cask "font-monoid"
cask "font-source-code-pro"
cask "fork"
cask "fsnotes"
cask "gas-mask"
cask "gb-studio"
cask "gog-galaxy"
cask "google-chrome"
cask "google-featured-photos"
cask "google-photos-backup-and-sync"
cask "graphiql"
cask "graphql-playground"
cask "hedgewars"
cask "iina"
cask "insomnia"
cask "intellij-idea"
cask "iterm2-beta"
cask "kaleidoscope"
cask "kap"
cask "karabiner-elements"
cask "kitematic"
cask "libreoffice"
cask "little-snitch"
cask "mamp"
cask "marked"
cask "micro-snitch"
cask "minecraft"
cask "minikube"
cask "netnewswire"
cask "notable"
cask "now"
cask "numi"
cask "nvalt"
cask "obs"
cask "openemu"
cask "openmw"
cask "openttd"
cask "opera"
cask "polar-bookshelf"
cask "postbox"
cask "postman"
cask "qlcolorcode"
cask "qlprettypatch"
cask "scapple"
cask "scrivener"
cask "sequel-pro"
cask "shotcut"
cask "signal"
cask "sketch-toolbox"
cask "sketch"
cask "spotify"
cask "steam"
cask "stremio"
cask "sublime-text"
cask "synthesia"
cask "telegram"
cask "tripmode"
cask "typora"
cask "vanilla"
cask "visual-studio-code"
cask "vlc"
cask "whatsapp"
mas "1Blocker", id: 1107421413
mas "Amphetamine", id: 937984704
mas "Byword", id: 420212497
mas "Deliveries", id: 924726344
mas "Dynamo", id: 1445910651
mas "ForkLift", id: 412448059
mas "iA Writer", id: 775737590
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Kindle", id: 405399194
mas "Lightshot Screenshot", id: 526298438
mas "Magnet", id: 441258766
mas "Noizio", id: 928871589
mas "Pages", id: 409201541
mas "PiPifier", id: 1160374471
mas "Pixelmator", id: 407963104
mas "Pocket", id: 568494494
mas "Reeder", id: 880001334
mas "Scida", id: 580917209
mas "The Unarchiver", id: 425424353
mas "TickTick", id: 966085870
mas "Trello", id: 1278508951
mas "Twitter", id: 409789998
mas "Unsplash Wallpapers", id: 1284863847
mas "Xcode", id: 497799835
